<table class="table">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td><?php echo $user->getUserProfile()->getFirstName(); ?></td>
            <td><?php echo $user->getUserProfile()->getLastName(); ?></td>
            <td><?php echo $user->getEmail(); ?></td>
            <td>
                <a href="/user/update/<?php echo $user->getId(); ?>">Update</a> 
                <a href="/user/delete/<?php echo $user->getId(); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
