<?php
    $formUser->setAttribute('action', $this->url('user', array('action' => 'login')))->prepare();
    $user = $formUser->get('user');
?>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h1 class="text-center">Login</h1>
</div>
<div class="modal-body">
    <?php echo $this->form()->openTag($formUser); ?>
        <div class="form-group">
            <?php 
                if ($this->messages){
                    echo '<ul>';
                    foreach($this->messages as $message)
                    {
                        echo '<li>'.$message.'</li>';
                    }
                    echo '</ul>';
                }
            ?>
        </div>
        <div class="form-group">
            <?php echo $this->formElement($user->get('email')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formElement($user->get('password')); ?>
        </div>
        <div class="form-group">
            <?php
            echo $this->formHidden($formUser->get('csrf'));
            echo $this->formElement($formUser->get('submit'));
            ?>
        </div>
    <?php echo $this->form()->closeTag(); ?>
</div>
