<?php
    $userRegForm->setAttribute('action', $this->url('user', array('action' => 'login')))->prepare();
    $user = $userRegForm->get('user');
    $userProfile = $userRegForm->get('user-profile');
    $role = $userRegForm->get('role');
?>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h1 class="text-center">Login</h1>
</div>
<div class="modal-body">
    <?php echo $this->form()->openTag($userRegForm); ?>
        <div class="form-group">
            <?php 
                if ($this->messages){
                    echo '<ul>';
                    foreach($this->messages as $message)
                    {
                        echo '<li>'.$message.'</li>';
                    }
                    echo '</ul>';
                }
            ?>
        </div>
        <div class="form-group">
            <?php echo $this->formElement($user->get('email')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formElement($user->get('password')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formElement($userProfile->get('firstname')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formElement($userProfile->get('lastname')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formElement($userProfile->get('birthdate')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formElement($userProfile->get('phone')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formElement($userProfile->get('website')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formElement($role->get('role-select')); ?>
        </div>
        <div class="form-group">
            <?php
            echo $this->formHidden($userRegForm->get('csrf'));
            echo $this->formElement($userRegForm->get('submit'));
            ?>
        </div>
    <?php echo $this->form()->closeTag(); ?>
</div>
